# Generated by Django 3.1.1 on 2020-09-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique_for_date='deadline')),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(max_length=1000)),
                ('due_date', models.DateField()),
                ('max_amount', models.IntegerField(blank=True, null=True)),
                ('renewable', models.BooleanField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('area_of_study', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('us_citizen', models.BooleanField()),
                ('daca_status', models.BooleanField()),
                ('financial_need', models.BooleanField()),
                ('hbcu', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
