# Generated by Django 3.1.1 on 2021-01-07 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colleges', '0002_collegestatus_user'),
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipstatus',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='association',
            field=models.ManyToManyField(blank=True, to='scholarships.Association'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='citizenship',
            field=models.ManyToManyField(blank=True, to='scholarships.Citizenship'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='college',
            field=models.ManyToManyField(blank=True, to='colleges.College'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='degree',
            field=models.ManyToManyField(blank=True, to='scholarships.Degree'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='disability',
            field=models.ManyToManyField(blank=True, to='scholarships.Disability'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='gender',
            field=models.ManyToManyField(blank=True, to='scholarships.Gender'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='heritage',
            field=models.ManyToManyField(blank=True, to='scholarships.Heritage'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='interest',
            field=models.ManyToManyField(blank=True, to='scholarships.Interest'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='military',
            field=models.ManyToManyField(blank=True, to='scholarships.Military'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scholarships.provider'),
        ),
        migrations.AddField(
            model_name='provider',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scholarships.state'),
        ),
        migrations.AddField(
            model_name='locationscholarship',
            name='location_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='scholarships.locationdetail'),
        ),
        migrations.AddField(
            model_name='locationscholarship',
            name='scholarship',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scholarships.scholarship'),
        ),
        migrations.AddField(
            model_name='locationscholarship',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='scholarships.state'),
        ),
        migrations.AddField(
            model_name='fieldscholarship',
            name='field_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='scholarships.fieldcategory'),
        ),
        migrations.AddField(
            model_name='fieldscholarship',
            name='field_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='scholarships.fielddetail'),
        ),
        migrations.AddField(
            model_name='fieldscholarship',
            name='scholarship',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scholarships.scholarship'),
        ),
        migrations.AddField(
            model_name='educationscholarship',
            name='education_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='scholarships.educationcategory'),
        ),
        migrations.AddField(
            model_name='educationscholarship',
            name='education_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='scholarships.educationdetail'),
        ),
        migrations.AddField(
            model_name='educationscholarship',
            name='scholarship',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scholarships.scholarship'),
        ),
    ]
