# Generated by Django 3.1.1 on 2020-12-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0004_auto_20201213_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarshipstatus',
            options={'verbose_name_plural': 'scholarship statuses'},
        ),
    ]
