# Generated by Django 3.1.1 on 2020-12-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0011_auto_20201109_1133'),
        ('scholarships', '0004_auto_20201213_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='college',
            field=models.ManyToManyField(blank=True, to='colleges.College'),
        ),
    ]
