# Generated by Django 3.0.1 on 2020-04-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0004_auto_20200425_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
