# Generated by Django 3.1.1 on 2020-09-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0005_auto_20200425_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
