# Generated by Django 3.1.1 on 2020-12-18 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scholarships', '0006_auto_20201218_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='user',
            field=models.ManyToManyField(related_name='scholarship_status', to=settings.AUTH_USER_MODEL),
        ),
    ]
