# Generated by Django 3.1.1 on 2020-12-18 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0007_auto_20201218_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 12, 18, 13, 57, 30, 9342)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
