# Generated by Django 3.1.1 on 2020-09-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pronouns',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='pronoun'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='user type'),
        ),
    ]
