# Generated by Django 3.1.1 on 2020-09-28 03:43

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200923_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ethnicity',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ethnicity'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='found_from',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True, verbose_name='found from'), blank=True, null=True, size=None),
        ),
    ]
