# Generated by Django 3.0.1 on 2020-08-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='high_school_grad_year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='high school graduation year'),
        ),
    ]
