# Generated by Django 3.1.1 on 2020-11-04 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_deletedaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='phone number'),
        ),
    ]
