# Generated by Django 3.0.1 on 2020-08-12 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_organization_members'),
        ('users', '0007_auto_20200811_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='high_school_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.Organization'),
        ),
    ]
