# Generated by Django 3.1.1 on 2020-11-10 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201105_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='action',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
