# Generated by Django 3.0.1 on 2020-08-12 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_high_school_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='high_school_name',
            new_name='high_school',
        ),
    ]
