# Generated by Django 3.0.1 on 2020-08-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_organization_members'),
        ('users', '0007_auto_20200811_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
