# Generated by Django 3.0.1 on 2020-08-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_high_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
