# Generated by Django 3.1.1 on 2020-11-10 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201110_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='date',
        ),
        migrations.AddField(
            model_name='action',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='deletedaccount',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
