# Generated by Django 3.1.1 on 2020-09-12 18:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20200831_2138'),
        ('users', '0011_remove_customuser_terms_and_conditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='found_from_other_value',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='high_school',
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.ManyToManyField(to='organizations.Organization'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ethnicity',
            field=models.CharField(default=None, max_length=40, null=True, verbose_name='ethinicity'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='found_from',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25, null=True, verbose_name='found from'), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='income_quintile',
            field=models.CharField(default=None, max_length=4, null=True, verbose_name='income quintile'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pronouns',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='pronoun'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='user type'),
        ),
    ]
