# Generated by Django 3.1.1 on 2020-11-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201117_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='sat_score',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_test_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_contact_method',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='preferred contact method'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sat_math',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='SAT math'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sat_verbal',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='SAT verbal'),
        ),
    ]
