# Generated by Django 3.1.1 on 2020-09-13 22:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200912_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ethnicity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ethnicity'), default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='found_from',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True, verbose_name='found from'), default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='GPA'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='income_quintile',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='income quintile'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='preferred name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pronouns',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='pronoun'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='user type'),
        ),
    ]
