# Generated by Django 3.1.1 on 2020-09-12 21:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200912_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ethnicity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25, null=True, verbose_name='ethnicity'), default=[], size=None),
            preserve_default=False,
        ),
    ]
