# Generated by Django 3.1.1 on 2020-09-12 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200912_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='high_school_name',
        ),
    ]
