# Generated by Django 3.1.1 on 2020-09-13 19:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200913_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ethnicity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True, verbose_name='ethnicity'), size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='found_from',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True, verbose_name='found from'), size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='preferred name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pronouns',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='pronoun'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='user type'),
        ),
    ]
