# Generated by Django 3.1.1 on 2020-09-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200913_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='income_quintile',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='income quintile'),
        ),
    ]
