# Generated by Django 3.1.1 on 2020-12-24 15:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=255, unique=True)),
                ('addressee', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('zipcode', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('phone_number_ext', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'provider',
                'verbose_name_plural': 'providers',
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('website', models.TextField(blank=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('max_amount', models.IntegerField(blank=True, null=True)),
                ('renewable', models.BooleanField(blank=True, null=True)),
                ('number_awards', models.IntegerField(blank=True, null=True)),
                ('education_level', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None)),
                ('education_requirements', models.TextField(blank=True)),
                ('area_of_study', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None)),
                ('area_of_study_description', models.TextField(blank=True)),
                ('writing_competition', models.BooleanField(blank=True, null=True)),
                ('interest_description', models.CharField(blank=True, max_length=255, null=True)),
                ('association_requirement', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None)),
                ('location', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('ethnicity', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('min_gpa', models.FloatField(blank=True, null=True)),
                ('max_gpa', models.FloatField(blank=True, null=True)),
                ('min_act', models.IntegerField(blank=True, null=True)),
                ('min_sat', models.IntegerField(blank=True, null=True)),
                ('disability', models.TextField(blank=True)),
                ('military', models.TextField(blank=True)),
                ('citizenship', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None)),
                ('first_generation', models.BooleanField(blank=True, null=True)),
                ('financial_need', models.BooleanField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'scholarship',
                'verbose_name_plural': 'scholarships',
            },
        ),
        migrations.CreateModel(
            name='ScholarshipStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('scholarship', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scholarship.scholarship')),
            ],
            options={
                'verbose_name': 'scholarhip status',
                'verbose_name_plural': 'scholarship status',
            },
        ),
    ]
