# Generated by Django 3.1.1 on 2020-12-26 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scholarship', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('college', '0002_auto_20201226_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipstatus',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='college',
            field=models.ManyToManyField(blank=True, to='college.College'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scholarship.provider'),
        ),
    ]
