# Generated by Django 3.1.1 on 2020-11-30 15:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0011_auto_20201109_1133'),
        ('scholarships', '0002_scholarship_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number_ext', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='category',
            new_name='interest_description',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='author',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='daca_status',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='hbcu',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='url',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='us_citizen',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='area_of_study_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='association_requirement',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='citizenship',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='college',
            field=models.ManyToManyField(to='colleges.College'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='disability',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='education_level',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='education_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='first_generation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='max_gpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='military',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='min_act',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='min_gpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='min_sat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='number_awards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='website',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='writing_competition',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='area_of_study',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='ethnicity',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='financial_need',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scholarships.contact'),
            preserve_default=False,
        ),
    ]
