sudo: required
services:
  - docker

before_script:
  - docker-compose -f docker-compose.prod.yml up -d --build

script:
  - docker-compose exec app python manage.py test

after_success:
  - docker build -t snagalingam/tilt-app ./app
  - docker build -t snagalingam/tilt-nginx ./nginx
  # log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push snagalingam/tilt-app
  - docker push snagalingam/tilt-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: tilt
  env: tilt-env
  bucket_name: test
  bucket_path: test
  on:
    branch: production
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
