sudo: required

language: python

env:
  global:
    - AWS_ACCESS_KEY_ID=B21n5MAVwGfpt1ytuSROwcxxaXQxfnwsuqUbwS9TSE/vWcFkyE0htyYpqZQDAvOcCqYlfCgK6EwkFDnPMImTHzLYK1g7kIKI1oGRIhADDdxC+4P59k4HKmnslyyZ2FCRo8MyZoypUH1VhD/nXbHBuieThi77LRsq3yxYWnNCveDN5yb9YVuxMkT7t60vQXCyc8EeEPMir0FnUToZzhqWbBHG3MfLj5q1Bgdy//32kwxZ1+VHOCOaZelIB0vZZmoFLbXqoBXZxD/L0/fcFNZd8ItTKYtFUo7CbbaoMMCi6VBD+2ivKMY6nqXujSXu8rLUgzQrORAwOL4qgjSGw9joHDLQXXTStR+gnFrMvHh2Las2FvImtw8tu+37VpV3vh1sZ4+hJLnjfnHGhWtrxYRMOujMVreavI7VAS73n5TTHB1tXMPD8GKfb+Yzum4SyXtRaaVVV3zjw9cOuz/BXf2ddw1D1l7pG59sC3gxQBHeepeie6wOdTazXWzToAfL10+d15YLtYNZuy1YsIIzUy8uaeZ7YR3J0XwnbHQSmZyDYdR6I9ugf3elhtvjhqKwLkNvuNdvkRyw9QHBJ45ZVezg139wFnfoqM5+9NHsYDz/C+AoXdpUUbqG1r2i5h3ylzBTVGXaaXkEnHaAdvL+vQI8hYKVMoh5c50jwHqKclYli2o=
    - AWS_ECR_ACCOUNT=614818178581
    - AWS_SECRET_ACCESS_KEY=LLR7mTCj90qed5Bw3fXfAGdIpQC8QHp+2TVHENQTRCXPYZkK/+drhRySHSueLllX7zItXj214VG8E9+yVZcyNCqiE5QAZsJeE9idoO4MUZwK0GULvacwVXg4T5lZUdqhWLZtgO4oJ0lL61ksNh23z5mONB0cguSjDzc3DjkiRCZ55D0JE/bRuQ2M5fE90bI/eyjXO3Ipeb19V6dFhcvvzULY1RO73m80zn1IzqT0VSrXuDbrAQ8veKEgmPP73PbzD4JdaZq8hYhP4D5OYRXWZKbMsIoRUPmNvdENF3fYiKPK/FmkTwB6nUMiWHuvE1xMJxvoVnZPiimdU28kr5CwoslF2dQVSE45XeRJzaW6hBWsTF6fblUnmcd5zBVA8s29bDlLhrnWTqT8gZRuk7C/O9YOr+tekDHD6c6/Y2D6elqfm+dSBKs1EOFAUV54Cc/fYc346MUb72A1AOxmkpFI79TMvtWktfKuOarUuP/GSoECooofuJlOJCBmCVwfDVxEPj5RE5+N6Zh+v+lw80vNlEwdC0hnjVVfbE0/r9gD+en0LFpRjEDedo8HHERO5xNP3g9UlVR88cwXox0fy1lk/jZKS1pI0kxCoxbHSZJVUJpzlSNi///w36j4dCC6veAlz8X7jQ66GfuGTVNlTO+2uWtrEvSh1TQbmQEXM3p9TNs=
    - PATH=$HOME/.local/bin:$PATH

services:
  - docker

before_script:
  - docker-compose -f docker-compose.prod.yml up -d --build

script:
  - docker-compose exec app python manage.py test

after_success:
  # install aws cli w/o sudo
  - pip install awscli
  #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
  - eval $(aws ecr get-login --no-include-email --region us-east-1)
  # take those images and push them to docker hub
  - docker tag tilt-app-staging:latest $AWS_ECR_ACCOUNT.dkr.ecr.us-east-2.amazonaws.com/tilt-app-staging:latest
  - docker tag tilt-nginx-staging:latest $AWS_ECR_ACCOUNT.dkr.ecr.us-east-2.amazonaws.com/tilt-nginx-staging:latest
  - docker push $AWS_ECR_ACCOUNT.dkr.ecr.us-east-2.amazonaws.com/tilt-app-staging:latest
  - docker push $AWS_ECR_ACCOUNT.dkr.ecr.us-east-2.amazonaws.com/tilt-nginx-staging:latest

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: tilt-staging
  env: Tiltstaging-env
  bucket_name: elasticbeanstalk-us-east-2-614818178581
  bucket_path: tilt-staging
  on:
    branch: feature/update-deployment
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
