version: '3.7'

services:
  backend:
    container_name: backend
    build: .
    command: gunicorn tilt_project.wsgi -b 0.0.0.0:8000
    environment:
      - REGION=us-east-2
      - ENVIRONMENT=development
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_USER=postgres
      - DEBUG=1
      - SECRET_KEY=((5qzn4=1s57*63r48lqkvz%60d#&_@b4w5f05$$6)lu35r(^lm
      - TWILIO_ACCOUNT=AC98b578e279bfd3dd82729b5743603aa6
      - TWILIO_AUTH=88f465a9722cd42d8545be2d997e9f65
      - TWILIO_NUMBER=+15625125600
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:11
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - 5050:5050
