version: '3.7'

services:

  backend:
    container_name: backend
    build: .
    command: gunicorn tilt_project.wsgi -b 0.0.0.0:8000
    environment:
      - ENVIRONMENT=development
      - SECRET_KEY=((5qzn4=1s57*63r48lqkvz%60d#&_@b4w5f05$$6)lu35r(^lm
      - DEBUG=1
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
