version: '3.7'

services:
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    command: gunicorn tilt_project.wsgi -b 0.0.0.0:8000
    container_name: backend
    depends_on:
      - db
    environment:
      - REGION=us-east-2
      - ENVIRONMENT=development
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_USER=postgres
      - DEBUG=1
      - SECRET_KEY=((5qzn4=1s57*63r48lqkvz%60d#&_@b4w5f05$$6)lu35r(^lm
    expose:
      - 8000
    volumes:
      - ./app:/app
  db:
    container_name: db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: postgres:12
    volumes:
      - dev_postgres:/var/lib/postgresql/data/

volumes:
  dev_postgres:
