version: '3.7'

services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn tilt.wsgi -b 0.0.0.0:8000
    environment:
      - AWS_BUCKET=financial-letters
      - AWS_LAMBDA_FUNCTION=wait-for-textract
      - AWS_REGION=us-east-2
      - ENVIRONMENT=development
      - GRAPHQL_ENDPOINT=https://localhost:8000/graphql
      - DATABASE_HOST=tilt-staging-postgres-test.co1g8hkhkrwp.us-east-2.rds.amazonaws.com
      - DATABASE_NAME=tiltstaging
      - DATABASE_PASSWORD=tiltstaging
      - DATABASE_USER=tiltstaging
      - DEBUG=1
      - SECRET_KEY=rUDX9ep7!&@YszbBaREjM2zAXqydPmvCz%Z5Hh4xBAdu3!V
      - TWILIO_PHONE_NUMBER=+15624721665
      - SENDER_NAME=Tilt
      - TILT_APP=staging
    expose:
      - 8000
    image: 614818178581.dkr.ecr.us-east-2.amazonaws.com/tilt-app-staging:latest
    volumes:
      - static_volume:/home/app/staticfiles

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    container_name: nginx
    depends_on:
      - app
    image: 614818178581.dkr.ecr.us-east-2.amazonaws.com/tilt-nginx-staging:latest
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - static_volume:/home/app/staticfiles
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

volumes:
  static_volume:
