version: '3.7'

services:
  backend:
    container_name: backend
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - AWS_BUCKET=financial-letters
      - AWS_LAMBDA_FUNCTION=wait-for-textract
      - AWS_REGION=us-east-2
      - ENVIRONMENT=development
      - GRAPHQL_ENDPOINT=https://localhost:8000/graphql
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_USER=postgres
      - DEBUG=1
      - SECRET_KEY=rUDX9ep7!&@YszbBaREjM2zAXqydPmvCz%Z5Hh4xBAdu3!V
      - TWILIO_PHONE_NUMBER=+15624721665
      - SENDER_NAME=Tilt
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    depends_on:
      - db

  db:
    container_name: db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: postgres:12
    volumes:
      - dev_postgres:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - 5050:5050

volumes:
  dev_postgres:
