# Generated by Django 3.0.1 on 2020-04-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_scholarship_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='amount_descriptor',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='posted_by',
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
