# Generated by Django 3.1.1 on 2020-12-26 14:38

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='business_status',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='icon',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='place_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='types',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(default='', max_length=255), blank=True, default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='organization',
            name='url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.TextField(default=''),
        ),
    ]
