# Generated by Django 3.0.1 on 2020-08-08 00:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='formatted_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='geo_location',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='formatted_phone_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='partnership',
            new_name='tilt_partnership',
        ),
        migrations.AddField(
            model_name='organization',
            name='lat',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='lng',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True), default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='organization',
            name='business_status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='place_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
