# Generated by Django 3.0.1 on 2020-07-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20200728_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='formatted_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
