# Generated by Django 3.1.1 on 2021-01-07 14:52

from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AidCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('primary', models.CharField(max_length=50)),
                ('secondary', models.CharField(max_length=50)),
                ('tertiary', models.CharField(blank=True, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'aid category',
                'verbose_name_plural': 'aid categories',
            },
        ),
        migrations.CreateModel(
            name='DocumentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255, unique=True)),
                ('words', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None)),
                ('tables', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'document data',
                'verbose_name_plural': 'document data',
            },
        ),
        migrations.CreateModel(
            name='DocumentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255, unique=True)),
                ('words_id', models.CharField(blank=True, max_length=255)),
                ('tables_id', models.CharField(blank=True, max_length=255)),
                ('sent', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('pass_fail', models.CharField(blank=True, max_length=255)),
                ('number_of_missing', models.PositiveIntegerField(blank=True, null=True)),
                ('missing_amounts', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'document result',
                'verbose_name_plural': 'document results',
            },
        ),
        migrations.CreateModel(
            name='AidSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.PositiveIntegerField()),
                ('total_aid', models.PositiveIntegerField()),
                ('net_price', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('college_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='colleges.collegestatus')),
            ],
            options={
                'verbose_name': 'aid summary',
                'verbose_name_plural': 'aid summaries',
            },
        ),
        migrations.CreateModel(
            name='AidData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField()),
                ('row_text', models.TextField(blank=True)),
                ('table', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('row_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('col_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('aid_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='financial_aid.aidcategory')),
                ('college_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='colleges.collegestatus')),
            ],
            options={
                'verbose_name': 'aid data',
                'verbose_name_plural': 'aid data',
            },
        ),
    ]
