# Generated by Django 3.1.1 on 2020-12-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_aid', '0002_aidcategory_aiddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidcategory',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
