# Generated by Django 3.1.1 on 2021-02-01 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_aid', '0003_auto_20210127_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiddata',
            name='other_source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aiddata',
            name='document_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial_aid.documentresult'),
        ),
        migrations.AlterField(
            model_name='documenterror',
            name='document_result',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financial_aid.documentresult'),
        ),
    ]
