# Generated by Django 3.1.1 on 2021-02-06 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0004_auto_20210201_1532'),
        ('financial_aid', '0004_auto_20210201_1532'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AidData',
            new_name='AidRawData',
        ),
        migrations.AlterModelOptions(
            name='aidrawdata',
            options={'verbose_name': 'aid raw data', 'verbose_name_plural': 'aid raw data'},
        ),
        migrations.CreateModel(
            name='AidFinalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('aid_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='financial_aid.aidcategory')),
                ('college_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='colleges.collegestatus')),
            ],
            options={
                'verbose_name': 'aid final data',
                'verbose_name_plural': 'aid final data',
            },
        ),
    ]
