# Generated by Django 3.1.1 on 2020-12-21 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_aid', '0006_auto_20201217_1225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BucketCheck',
        ),
        migrations.DeleteModel(
            name='BucketResult',
        ),
        migrations.AlterModelOptions(
            name='aidcategory',
            options={'verbose_name_plural': 'Aid categories'},
        ),
    ]
