# Generated by Django 3.1.1 on 2020-12-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_aid', '0006_auto_20201215_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiddata',
            old_name='college_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='college_status',
            new_name='status',
        ),
    ]
