# Generated by Django 3.1.1 on 2020-12-21 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0013_auto_20201221_1219'),
        ('financial_aid', '0006_auto_20201217_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiddata',
            name='college_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.status'),
        ),
    ]
