# Generated by Django 3.1.1 on 2020-12-22 19:14

from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('college_status', '0005_auto_20201222_1914'),
        ('financial_aid', '0007_auto_20201221_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiddata',
            name='aid_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financial_aid.aidcategory'),
        ),
        migrations.AlterField(
            model_name='aiddata',
            name='college_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='college_status.status'),
        ),
        migrations.AlterField(
            model_name='aiddata',
            name='row_data',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
