# Generated by Django 3.1.1 on 2020-12-21 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_status', '0006_auto_20201221_1817'),
        ('financial_aid', '0007_auto_20201221_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiddata',
            name='college_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_status.collegestatus'),
        ),
    ]
