# Generated by Django 3.1.1 on 2020-12-21 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0014_auto_20201221_1614'),
        ('financial_aid', '0007_auto_20201221_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='AidSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.IntegerField(blank=True, null=True)),
                ('total_aid', models.IntegerField(blank=True, null=True)),
                ('net_price', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('college_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.collegestatus')),
            ],
            options={
                'verbose_name_plural': 'Aid summaries',
            },
        ),
        migrations.DeleteModel(
            name='BucketCheck',
        ),
        migrations.DeleteModel(
            name='BucketResult',
        ),
        migrations.AlterModelOptions(
            name='aidcategory',
            options={'verbose_name_plural': 'Aid categories'},
        ),
        migrations.AlterField(
            model_name='aiddata',
            name='college_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.collegestatus'),
        ),
    ]
