# Generated by Django 3.1.1 on 2020-11-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201110_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedaccount',
            name='date',
            field=models.DateField(),
        ),
    ]
