# Generated by Django 3.1.1 on 2020-09-15 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='students',
            field=models.ManyToManyField(related_name='to_organization', to=settings.AUTH_USER_MODEL),
        ),
    ]
