# Generated by Django 3.1.1 on 2020-09-23 23:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20200916_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=None, null=True, size=None),
        ),
    ]
