# Generated by Django 3.0.1 on 2020-08-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_organization_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='lat',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='lng',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
