# Generated by Django 3.0.1 on 2020-08-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20200831_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='lat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='lng',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
