# Generated by Django 3.0.1 on 2020-08-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20200831_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.TextField(blank=True, null=True),
        ),
    ]
