# Generated by Django 3.1.1 on 2020-09-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20200831_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='tilt_partnership',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
