# Generated by Django 3.1.1 on 2020-09-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20200912_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='business_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
