# Generated by Django 3.1.1 on 2020-12-24 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegestatus',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget',
            name='college_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='college.collegestatus'),
        ),
    ]
