# Generated by Django 3.1.1 on 2021-01-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_aid', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AidSummary',
        ),
    ]
