# Generated by Django 3.1.1 on 2021-01-27 09:57

from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_auto_20210117_1455'),
        ('financial_aid', '0002_delete_aidsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'document error',
                'verbose_name_plural': 'document errors',
            },
        ),
        migrations.DeleteModel(
            name='DocumentData',
        ),
        migrations.RenameField(
            model_name='aiddata',
            old_name='row_index',
            new_name='row_num',
        ),
        migrations.RenameField(
            model_name='aiddata',
            old_name='table',
            new_name='table_num',
        ),
        migrations.RenameField(
            model_name='documentresult',
            old_name='missing_amounts',
            new_name='comparison_missing_amounts',
        ),
        migrations.RenameField(
            model_name='documentresult',
            old_name='number_of_missing',
            new_name='comparison_missing_num',
        ),
        migrations.RenameField(
            model_name='documentresult',
            old_name='tables_id',
            new_name='table_job_id',
        ),
        migrations.RenameField(
            model_name='documentresult',
            old_name='words_id',
            new_name='text_job_id',
        ),
        migrations.RemoveField(
            model_name='aiddata',
            name='col_index',
        ),
        migrations.RemoveField(
            model_name='documentresult',
            name='pass_fail',
        ),
        migrations.RemoveField(
            model_name='documentresult',
            name='processed',
        ),
        migrations.AddField(
            model_name='aiddata',
            name='document_result',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='financial_aid.documentresult'),
        ),
        migrations.AddField(
            model_name='documentresult',
            name='automated_review_succeeded',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentresult',
            name='college_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='colleges.collegestatus'),
        ),
        migrations.AddField(
            model_name='documentresult',
            name='table_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentresult',
            name='table_succeeded',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentresult',
            name='text_data',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='documentresult',
            name='text_succeeded',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiddata',
            name='row_text',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='documenterror',
            name='document_result',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='financial_aid.documentresult'),
        ),
    ]
