# Generated by Django 3.1.1 on 2020-12-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_aid', '0004_documentresult_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentresult',
            name='reviewed',
        ),
        migrations.RemoveField(
            model_name='documentresult',
            name='user',
        ),
    ]
