# Generated by Django 3.1.1 on 2020-12-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_aid', '0005_auto_20201213_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiddata',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
