# Generated by Django 3.1.1 on 2020-09-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
