# Generated by Django 3.1.1 on 2020-09-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_auto_20200916_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
