# Generated by Django 3.1.1 on 2021-01-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_collegestatus_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegestatus',
            name='award_net_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegestatus',
            name='award_scorecard_cost_estimate',
            field=models.CharField(blank=True, choices=[('in-state tuition', 'in-state tuition'), ('out-of-state tuition', 'out-of-state tuition')], max_length=50),
        ),
        migrations.AddField(
            model_name='collegestatus',
            name='award_total_costs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegestatus',
            name='award_total_grants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestatus',
            name='award_status',
            field=models.CharField(blank=True, choices=[('uploaded', 'uploaded'), ('reviewed', 'reviewed'), ('emailed user', 'emailed user'), ('texted user', 'texted user')], max_length=255),
        ),
    ]
