# Generated by Django 3.1.1 on 2020-09-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_auto_20200916_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='lat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='lng',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
