# Generated by Django 3.0.1 on 2020-08-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_college_favicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='college_scorecard_id',
        ),
        migrations.AddField(
            model_name='college',
            name='ope_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='unit_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='lat',
            field=models.IntegerField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='lng',
            field=models.IntegerField(blank=True, max_length=250, null=True),
        ),
    ]
