# Generated by Django 3.0.1 on 2020-08-31 21:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_auto_20200831_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='business_status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='favicon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='lat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='lng',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='main_photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='photos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='college',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='website',
            field=models.TextField(blank=True, null=True),
        ),
    ]
