# Generated by Django 3.1.1 on 2020-09-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_auto_20200921_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
