# Generated by Django 3.1.1 on 2021-02-01 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_auto_20210117_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegestatus',
            name='award_scorecard_cost_estimate',
        ),
        migrations.AddField(
            model_name='collegestatus',
            name='most_affordable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collegestatus',
            name='residency',
            field=models.CharField(blank=True, choices=[('oncampus', 'oncampus'), ('offcampus not with family', 'offcampus not with family'), ('offcampus with family', 'offcampus with family')], max_length=255),
        ),
        migrations.CreateModel(
            name='Ipeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.PositiveIntegerField(null=True)),
                ('fees_in_state', models.PositiveIntegerField(blank=True, null=True)),
                ('fees_out_of_state', models.PositiveIntegerField(blank=True, null=True)),
                ('other_expenses_off_campus_not_with_family', models.PositiveIntegerField(blank=True, null=True)),
                ('other_expenses_off_campus_with_family', models.PositiveIntegerField(blank=True, null=True)),
                ('other_expenses_on_campus', models.PositiveIntegerField(blank=True, null=True)),
                ('room_on_campus', models.PositiveIntegerField(blank=True, null=True)),
                ('room_off_campus_not_with_family', models.PositiveIntegerField(blank=True, null=True)),
                ('tuition_in_state', models.PositiveIntegerField(blank=True, null=True)),
                ('tuition_out_of_state', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('college', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='colleges.college')),
            ],
            options={
                'verbose_name': 'ipeds',
                'verbose_name_plural': 'ipeds',
            },
        ),
    ]
