# Generated by Django 3.1.1 on 2020-09-28 03:43

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0004_auto_20200923_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='photos',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='college',
            name='types',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=None, null=True, size=None),
        ),
    ]
