# Generated by Django 3.1.1 on 2021-03-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0004_auto_20210201_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegestatus',
            name='award_costs_missing',
            field=models.BooleanField(default=False),
        ),
    ]
