# Generated by Django 3.1.1 on 2020-10-05 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0006_scorecard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorecard',
            name='degree_urbanization',
        ),
        migrations.AddField(
            model_name='scorecard',
            name='carnegie_size_setting_residential',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='carnegie_size_setting_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='locale_updated',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_agriculture',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_architecture',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_biological',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_business_marketing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_communication',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_communications_technology',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_computer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_construction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_education',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_engineering',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_engineering_technology',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_english',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_ethnic_cultural_gender',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_family_consumer_science',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_health',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_history',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_humanities',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_language',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_legal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_library',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_mathematics',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_mechanic_repair_technology',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_military',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_multidiscipline',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_parks_recreation_fitness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_personal_culinary',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_philosophy_religious',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_physical_science',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_precision_production',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_psychology',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_public_administration_social_service',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_resources',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_science_technology',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_security_law_enforcement',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_social_science',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_theology_religious_vocation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_transportation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='program_percentage_visual_performing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cip_code', models.CharField(blank=True, max_length=255, null=True)),
                ('cip_title', models.CharField(blank=True, max_length=255, null=True)),
                ('credential_level', models.CharField(blank=True, max_length=255, null=True)),
                ('credential_title', models.CharField(blank=True, max_length=255, null=True)),
                ('num_students_debt', models.IntegerField(blank=True, null=True)),
                ('median_debt', models.IntegerField(blank=True, null=True)),
                ('monthly_debt_payment', models.IntegerField(blank=True, null=True)),
                ('mean_debt', models.IntegerField(blank=True, null=True)),
                ('num_students_titleiv', models.IntegerField(blank=True, null=True)),
                ('num_students_earnings', models.IntegerField(blank=True, null=True)),
                ('median_earnings', models.IntegerField(blank=True, null=True)),
                ('num_students_ipeds_awards1', models.IntegerField(blank=True, null=True)),
                ('num_students_ipeds_awards2', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.college')),
            ],
        ),
    ]
