# Generated by Django 3.1.1 on 2020-10-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0007_auto_20201005_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='unit_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
