# Generated by Django 3.1.1 on 2020-10-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0008_auto_20201006_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='main_campus',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='men_only',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='minority_serving_aanipi',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='minority_serving_annh',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='minority_serving_hispanic',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='minority_serving_historically_black',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='minority_serving_nant',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='minority_serving_predominantly_black',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='minority_serving_tribal',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='online_only',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='open_admissions',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='operating',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='under_investigation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='women_only',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
