# Generated by Django 3.1.1 on 2020-11-09 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0010_auto_20201015_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldofstudy',
            options={'verbose_name_plural': 'field of studies'},
        ),
    ]
