# Generated by Django 3.1.1 on 2020-12-21 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0011_auto_20201109_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldofstudy',
            options={'verbose_name_plural': 'Fields of study'},
        ),
    ]
