# Generated by Django 3.1.1 on 2020-12-21 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0012_status'),
    ]

    operations = [
    ]
