# Generated by Django 3.1.1 on 2020-12-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0013_auto_20201221_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_study', models.IntegerField(blank=True, null=True)),
                ('job', models.IntegerField(blank=True, null=True)),
                ('savings', models.IntegerField(blank=True, null=True)),
                ('family', models.IntegerField(blank=True, null=True)),
                ('other_scholarships', models.IntegerField(blank=True, null=True)),
                ('loan_subsidized', models.IntegerField(blank=True, null=True)),
                ('loan_unsubsidized', models.IntegerField(blank=True, null=True)),
                ('loan_plus', models.IntegerField(blank=True, null=True)),
                ('loan_private', models.IntegerField(blank=True, null=True)),
                ('loan_school', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('net_price', models.IntegerField(blank=True, null=True)),
                ('award_uploaded', models.BooleanField(default=False)),
                ('award_reviewed', models.BooleanField(default=False)),
                ('user_notified', models.BooleanField(default=False)),
                ('residency', models.CharField(blank=True, max_length=255, null=True)),
                ('in_state_tuition', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'College statuses',
            },
        ),
        migrations.RemoveField(
            model_name='status',
            name='college',
        ),
        migrations.RemoveField(
            model_name='status',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='fieldofstudy',
            options={'verbose_name_plural': 'Field of studies'},
        ),
    ]
