# Generated by Django 3.1.1 on 2020-12-21 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0014_auto_20201221_1614'),
    ]

operations = [
                migrations.RunSQL("""
            INSERT INTO colleges_collegestatus (
                id,
                user_id,
                college_id,
                status,
                net_price,
                award_uploaded,
                award_reviewed,
                user_notified,
                created,
                updated
            )
            SELECT
                id,
                user_id,
                college_id,
                status,
                net_price,
                award_uploaded,
                award_reviewed,
                user_notified,
                created,
                updated
            FROM
                colleges_status;
        """, reverse_sql="""
            INSERT INTO colleges_status (
                id,
                user_id,
                college_id,
                status,
                net_price,
                award_uploaded,
                award_reviewed,
                user_notified,
                created,
                updated
            )
            SELECT
                id,
                user_id,
                college_id,
                status,
                net_price,
                award_uploaded,
                award_reviewed,
                user_notified,
                created,
                updated
            FROM
                colleges_collegestatus;
        """)
    ]
