# Generated by Django 3.1.1 on 2020-12-21 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colleges', '0014_auto_20201221_1614'),
        ('financial_aid', '0008_auto_20201221_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='collegestatus',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.college'),
        ),
        migrations.AddField(
            model_name='collegestatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget',
            name='college_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.collegestatus'),
        ),
    ]
