# Generated by Django 3.1.1 on 2020-12-21 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_aid', '0008_auto_20201221_1817'),
        ('colleges', '0015_auto_20201221_1720'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='CollegeStatus',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AlterModelOptions(
            name='fieldofstudy',
            options={'verbose_name_plural': 'field of studies'},
        ),
    ]
