# Pull base image
FROM python:3.8

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set working directory
ENV APP_HOME=/app
WORKDIR $APP_HOME

# Install Python dependencies
COPY Pipfile Pipfile.lock $APP_HOME/
RUN pip install pipenv && pipenv install --system

# Add the rest of the code
COPY . $APP_HOME/

# SECRET_KEY is only included here to avoid raising an error when generating static files.
# Be sure to add a real SECRET_KEY config variable in deployment.
RUN SECRET_KEY=somethingsupersecret \
  python3 manage.py collectstatic --noinput

# Run entrypoint.sh that verifies that Postgres is healthy before applying the migrations
ENTRYPOINT ["./entrypoint.prod.sh"]
