CARNEGIE_BASIC_DICT = {
    -2: "",
    0: "",
    1: "Associate's Colleges: High Transfer-High Traditional",
    2: "Associate's Colleges: High Transfer-Mixed Traditional/Nontraditional",
    3: "Associate's Colleges: High Transfer-High Nontraditional",
    4: "Associate's Colleges: Mixed Transfer/Career & Technical-High Traditional",
    5: "Associate's Colleges: Mixed Transfer/Career & Technical-Mixed Traditional/Nontraditional",
    6: "Associate's Colleges: Mixed Transfer/Career & Technical-High Nontraditional",
    7: "Associate's Colleges: High Career & Technical-High Traditional",
    8: "Associate's Colleges: High Career & Technical-Mixed Traditional/Nontraditional",
    9: "Associate's Colleges: High Career & Technical-High Nontraditional",
    10: "Special Focus Two-Year: Health Professions",
    11: "Special Focus Two-Year: Technical Professions",
    12: "Special Focus Two-Year: Arts & Design",
    13: "Special Focus Two-Year: Other Fields",
    14: "Baccalaureate/Associate's Colleges: Associate's Dominant",
    15: "Doctoral Universities: Very High Research Activity",
    16: "Doctoral Universities: High Research Activity",
    17: "Doctoral/Professional Universities",
    18: "Master's Colleges & Universities: Larger Programs",
    19: "Master's Colleges & Universities: Medium Programs",
    20: "Master's Colleges & Universities: Small Programs",
    21: "Baccalaureate Colleges: Arts & Sciences Focus",
    22: "Baccalaureate Colleges: Diverse Fields",
    23: "Baccalaureate/Associate's Colleges: Mixed Baccalaureate/Associate's",
    24: "Special Focus Four-Year: Faith-Related Institutions",
    25: "Special Focus Four-Year: Medical Schools & Centers",
    26: "Special Focus Four-Year: Other Health Professions Schools",
    27: "Special Focus Four-Year: Engineering Schools",
    28: "Special Focus Four-Year: Other Technology-Related Schools",
    29: "Special Focus Four-Year: Business & Management Schools",
    30: "Special Focus Four-Year: Arts, Music & Design Schools",
    31: "Special Focus Four-Year: Law Schools",
    32: "Special Focus Four-Year: Other Special Focus Institutions",
    33: "Tribal Colleges"
}

CARNEGIE_SIZE_SETTING_DICT = {
    -2: "",
    0: "",
    1: "Two-year, very small",
    2: "Two-year, small",
    3: "Two-year, medium",
    4: "Two-year, large",
    5: "Two-year, very large",
    6: "Four-year, very small, primarily nonresidential",
    7: "Four-year, very small, primarily residential",
    8: "Four-year, very small, highly residential",
    9: "Four-year, small, primarily nonresidential",
    10: "Four-year, small, primarily residential",
    11: "Four-year, small, highly residential",
    12: "Four-year, medium, primarily nonresidential",
    13: "Four-year, medium, primarily residential",
    14: "Four-year, medium, highly residential",
    15: "Four-year, large, primarily nonresidential",
    16: "Four-year, large, primarily residential",
    17: "Four-year, large, highly residential",
    18: "Exclusively graduate/professional",
}

CARNEGIE_SIZE_SETTING_SIZE_DICT = {
    -2: "",
    0: "",
    1: "Very Small",
    2: "Small",
    3: "Medium",
    4: "Large",
    5: "Very Large",
    6: "Very Small",
    7: "Very Small",
    8: "Very Small",
    9: "Small",
    10: "Small",
    11: "Small",
    12: "Medium",
    13: "Medium",
    14: "Medium",
    15: "Large",
    16: "Large",
    17: "Large",
    18: "",
}

CARNEGIE_SIZE_SETTING_RESIDENTIAL_DICT = {
    -2: "",
    0: "",
    1: "Commuter",
    2: "Commuter",
    3: "Commuter",
    4: "Commuter",
    5: "Commuter",
    6: "Primarily Commuter",
    7: "Primarily Residential",
    8: "Highly Residential",
    9: "Primarily Commuter",
    10: "Primarily Residential",
    11: "Highly Residential",
    12: "Primarily Commuter",
    13: "Primarily Residential",
    14: "Highly Residential",
    15: "Primarily Commuter",
    16: "Primarily Residential",
    17: "Highly Residential",
    18: "",
}

CARNEGIE_UNDERGRAD_DICT = {
    -2: "",
    0: "",
    1: "Two-year, higher part-time",
    2: "Two-year, mixed part/full-time",
    3: "Two-year, medium full-time",
    4: "Two-year, higher full-time",
    5: "Four-year, higher part-time",
    6: "Four-year, medium full-time, inclusive, lower transfer-in",
    7: "Four-year, medium full-time, inclusive, higher transfer-in",
    8: "Four-year, medium full-time, selective, lower transfer-in",
    9: "Four-year, medium full-time, selective, higher transfer-in",
    10: "Four-year, full-time, inclusive, lower transfer-in",
    11: "Four-year, full-time, inclusive, higher transfer-in",
    12: "Four-year, full-time, selective, lower transfer-in",
    13: "Four-year, full-time, selective, higher transfer-in",
    14: "Four-year, full-time, more selective, lower transfer-in",
    15: "Four-year, full-time, more selective, higher transfer-in",
}

CREDENTIAL_LEVEL_DICT = {
    1: "Undergraduate Certificate or Diploma",
    2: "Associate's Degree",
    3: "Bachelor’s Degree",
    4: "Post-baccalaureate Certificate",
    5: "Master's Degree",
    6: "Doctoral Degree",
    7: "First Professional Degree",
    8: "Graduate/Professional Certificate",
}

HIGHEST_DEGREE_AWARDED_DICT = {
    0: "Non-degree-granting",
    1: "Certificate degree",
    2: "Associate degree",
    3: "Bachelor's degree",
    4: "Graduate degree",
}

INSTITUTIONAL_LEVEL_DICT = {
    1: "4-year",
    2: "2-year",
    3: "Less-than-2-year",
}

LOCALE_DICT = {
    11: "City: Large(population of 250, 000 or more)",
    12: "City: Midsize(population of at least 100, 000 but less than 250, 000)",
    13: "City: Small(population less than 100, 000)",
    21: "Suburb: Large(outside principal city, in urbanized area with population of 250, 000 or more)",
    22: "Suburb: Midsize(outside principal city, in urbanized area with population of at least 100, 000 but less than 250, 000)",
    23: "Suburb: Small(outside principal city, in urbanized area with population less than 100, 000)",
    31: "Town: Fringe ( in urban cluster up to 10 miles from an urbanized area)",
    32: "Town: Distant ( in urban cluster more than 10 miles and up to 35 miles from an urbanized area)",
    33: "Town: Remote ( in urban cluster more than 35 miles from an urbanized area)",
    41: "Rural: Fringe(rural territory up to 5 miles from an urbanized area or up to 2.5 miles from an urban cluster)",
    42: "Rural: Distant(rural territory more than 5 miles but up to 25 miles from an urbanized area or more than 2.5 and up to 10 miles from an urban cluster)",
    43: "Rural: Remote(rural territory more than 25 miles from an urbanized area and more than 10 miles from an urban cluster)"
}

LOCALE_UPDATED_DICT = {
    11: "Larce City",
    12: "Midsize City",
    13: "Small City",
    21: "Large Suburb",
    22: "Midsize Suburb",
    23: "Small Suburb",
    31: "Town",
    32: "Town",
    33: "Town",
    41: "Rural",
    42: "Rural",
    43: "Rural"
}

OPEN_ADMISSIONS_DICT = {
    None: False,
    1: True,
    2: False,
    3: False,
}

OWNERSHIP_DICT = {
    1: "Public",
    2: "Private Nonprofit",
    3: "Private For-Profit",
}

PREDOMINANT_DEGREE_AWARDED_DICT = {
    None: "",
    0: "Not classified",
    1: "Predominantly certificate-degree granting",
    2: "Predominantly associate's-degree granting",
    3: "Predominantly bachelor's-degree granting",
    4: "Entirely graduate-degree granting",
}

REGION_DICT = {
    0: "U.S. Service Schools",
    1: "New England",
    2: "Mid East",
    3: "Great Lakes",
    4: "Plains",
    5: "Southeast",
    6: "Southwest",
    7: "Rocky Mountains",
    8: "Far West",
    9: "Outlying Areas",
}

RELIGIOUS_AFFILIATION_DICT = {
    None: "",
    -1: "",
    -2: "",
    22: "American Evangelical Lutheran Church",
    24: "African Methodist Episcopal Zion Church",
    27: "Assemblies of God Church",
    28: "Brethren Church",
    30: "Roman Catholic",
    33: "Wisconsin Evangelical Lutheran Synod",
    34: "Christ and Missionary Alliance Church",
    35: "Christian Reformed Church",
    36: "Evangelical Congregational Church",
    37: "Evangelical Covenant Church of America",
    38: "Evangelical Free Church of America",
    39: "Evangelical Lutheran Church",
    40: "International United Pentecostal Church",
    41: "Free Will Baptist Church",
    42: "Interdenominational",
    43: "Mennonite Brethren Church",
    44: "Moravian Church",
    45: "North American Baptist",
    47: "Pentecostal Holiness Church",
    48: "Christian Churches and Churches of Christ",
    49: "Reformed Church in America",
    50: "Episcopal Church, Reformed",
    51: "African Methodist Episcopal",
    52: "American Baptist",
    53: "American Lutheran",
    54: "Baptist",
    55: "Christian Methodist Episcopal",
    57: "Church of God",
    58: "Church of Brethren",
    59: "Church of the Nazarene",
    60: "Cumberland Presbyterian",
    61: "Christian Church(Disciples of Christ)",
    64: "Free Methodist",
    65: "Friends",
    66: "Presbyterian Church(USA)",
    67: "Lutheran Church in America",
    68: "Lutheran Church - Missouri Synod",
    69: "Mennonite Church",
    71: "United Methodist",
    73: "Protestant Episcopal",
    74: "Churches of Christ",
    75: "Southern Baptist",
    76: "United Church of Christ",
    77: "Protestant, not specified",
    78: "Multiple Protestant Denomination",
    79: "Other Protestant",
    80: "Jewish",
    81: "Reformed Presbyterian Church",
    84: "United Brethren Church",
    87: "Missionary Church Inc",
    88: "Undenominational",
    89: "Wesleyan",
    91: "Greek Orthodox",
    92: "Russian Orthodox",
    93: "Unitarian Universalist",
    94: "Latter Day Saints(Mormon Church)",
    95: "Seventh Day Adventists",
    97: "The Presbyterian Church in America",
    99: "Other(none of the above)",
    100: "Original Free Will Baptist",
    101: "Ecumenical Christian",
    102: "Evangelical Christian",
    103: "Presbyterian",
    105: "General Baptist",
    106: "Muslim",
    107: "Plymouth Brethren",
    108: ""
}


STATE_FIPS_DICT = {
    1: "Alabama",
    2: "Alaska",
    4: "Arizona",
    5: "Arkansas",
    6: "California",
    8: "Colorado",
    9: "Connecticut",
    10: "Delaware",
    11: "District of Columbia",
    12: "Florida",
    13: "Georgia",
    15: "Hawaii",
    16: "Idaho",
    17: "Illinois",
    18: "Indiana",
    19: "Iowa",
    20: "Kansas",
    21: "Kentucky",
    22: "Louisiana",
    23: "Maine",
    24: "Maryland",
    25: "Massachusetts",
    26: "Michigan",
    27: "Minnesota",
    28: "Mississippi",
    29: "Missouri",
    30: "Montana",
    31: "Nebraska",
    32: "Nevada",
    33: "New Hampshire",
    34: "New Jersey",
    35: "New Mexico",
    36: "New York",
    37: "North Carolina",
    38: "North Dakota",
    39: "Ohio",
    40: "Oklahoma",
    41: "Oregon",
    42: "Pennsylvania",
    44: "Rhode Island",
    45: "South Carolina",
    46: "South Dakota",
    47: "Tennessee",
    48: "Texas",
    49: "Utah",
    50: "Vermont",
    51: "Virginia",
    53: "Washington",
    54: "West Virginia",
    55: "Wisconsin",
    56: "Wyoming",
    60: "American Samoa",
    64: "Federated States of Micronesia",
    66: "Guam",
    69: "Northern Mariana Islands",
    70: "Palau",
    72: "Puerto Rico",
    78: "Virgin Islands"
}
