# Generated by Django 3.1.1 on 2020-09-21 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colleges', '0003_auto_20200921_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_status', models.CharField(blank=True, max_length=255, null=True)),
                ('net_price', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.college')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'college_statuses',
            },
        ),
    ]
