# Generated by Django 3.1.1 on 2020-09-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegestatus',
            options={'verbose_name_plural': 'College Statuses'},
        ),
    ]
