# Generated by Django 3.1.1 on 2020-09-23 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_status', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collegestatus',
            old_name='college_status',
            new_name='status',
        ),
    ]
