# Generated by Django 3.1.1 on 2020-09-28 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_status', '0002_auto_20200923_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collegestatus',
            old_name='college_id',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='collegestatus',
            old_name='user_id',
            new_name='user',
        ),
    ]
