# Generated by Django 3.1.1 on 2020-09-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_status', '0002_auto_20200921_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegestatus',
            options={'verbose_name_plural': 'college statuses'},
        ),
    ]
