# Generated by Django 3.1.1 on 2020-12-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_status', '0003_auto_20200928_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegestatus',
            name='award_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collegestatus',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collegestatus',
            name='user_notified',
            field=models.BooleanField(default=False),
        ),
    ]
