# Generated by Django 3.1.1 on 2020-12-15 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_aid', '0006_auto_20201215_1523'),
        ('colleges', '0012_status'),
        ('college_status', '0004_auto_20201213_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_study', models.IntegerField(blank=True, null=True)),
                ('job', models.IntegerField(blank=True, null=True)),
                ('savings', models.IntegerField(blank=True, null=True)),
                ('family', models.IntegerField(blank=True, null=True)),
                ('other_scholarships', models.IntegerField(blank=True, null=True)),
                ('loan_subsideized', models.IntegerField(blank=True, null=True)),
                ('loan_unsubsideized', models.IntegerField(blank=True, null=True)),
                ('loan_plus', models.IntegerField(blank=True, null=True)),
                ('loan_private', models.IntegerField(blank=True, null=True)),
                ('loan_school', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('college_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.status')),
            ],
        ),
        migrations.DeleteModel(
            name='CollegeStatus',
        ),
    ]
