# Generated by Django 3.1.1 on 2020-12-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_status', '0005_auto_20201215_1523'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
