# Generated by Django 3.1.1 on 2020-12-21 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0015_auto_20201221_1720'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('college_status', '0005_auto_20201221_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('net_price', models.IntegerField(blank=True, null=True)),
                ('award_uploaded', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('user_notified', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.college')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'college statuses',
            },
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
