FROM nginx

# delete the initial config file
RUN rm /etc/nginx/conf.d/default.conf

# copy our config file
COPY nginx.conf /etc/nginx/conf.d/nginx.conf
COPY certs/tiltstaging.crt /etc/nginx/certs/tiltstaging.crt
COPY certs/tiltstaging.key /etc/nginx/certs/tiltstaging.key

# Expose ports
EXPOSE 80
EXPOSE 443
