# Generated by Django 3.1.1 on 2020-12-26 14:12

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AidCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('primary', models.CharField(max_length=255)),
                ('secondary', models.CharField(max_length=255)),
                ('tertiary', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'aid category',
                'verbose_name_plural': 'aid categories',
            },
        ),
        migrations.CreateModel(
            name='AidData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('amount', models.PositiveIntegerField()),
                ('row_data', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default=''), blank=True, null=True, size=None)),
                ('table_number', models.PositiveIntegerField(blank=True, null=True)),
                ('row_index', models.PositiveIntegerField(blank=True, null=True)),
                ('col_index', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'aid data',
                'verbose_name_plural': 'aid data',
            },
        ),
        migrations.CreateModel(
            name='AidSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.IntegerField(blank=True, null=True)),
                ('total_aid', models.IntegerField(blank=True, null=True)),
                ('net_price', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'aid summary',
                'verbose_name_plural': 'aid summaries',
            },
        ),
        migrations.CreateModel(
            name='DocumentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255, unique=True)),
                ('words', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=255), blank=True, null=True, size=None)),
                ('tables', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'document data',
                'verbose_name_plural': 'document data',
            },
        ),
        migrations.CreateModel(
            name='DocumentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255, unique=True)),
                ('words_id', models.CharField(blank=True, max_length=255)),
                ('tables_id', models.CharField(blank=True, max_length=255)),
                ('sent', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('pass_fail', models.CharField(blank=True, max_length=255)),
                ('number_of_missing', models.PositiveIntegerField(blank=True, null=True)),
                ('missing_amounts', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=255), blank=True, null=True, size=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'document result',
                'verbose_name_plural': 'document results',
            },
        ),
    ]
