# Generated by Django 3.1.1 on 2020-12-26 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college', '0001_initial'),
        ('aid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidsummary',
            name='college_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='college.collegestatus'),
        ),
        migrations.AddField(
            model_name='aiddata',
            name='aid_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aid.aidcategory'),
        ),
        migrations.AddField(
            model_name='aiddata',
            name='college_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='college.collegestatus'),
        ),
    ]
