# Generated by Django 3.1.1 on 2020-12-24 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_better_admin_arrayfield.models.fields
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'unique': 'A user is already registered with this email address'}, max_length=254, unique=True, verbose_name='email address')),
                ('user_type', models.CharField(blank=True, default=None, max_length=255, verbose_name='user type')),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('preferred_name', models.CharField(blank=True, max_length=255, verbose_name='preferred name')),
                ('preferred_contact_method', models.CharField(blank=True, choices=[('text', 'text'), ('email', 'email')], max_length=255, verbose_name='preferred contact method')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='phone number')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_onboarded', models.BooleanField(default=False)),
                ('is_test', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='GPA')),
                ('act_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ACT score')),
                ('sat_math', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='SAT math')),
                ('sat_verbal', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='SAT verbal')),
                ('efc', models.PositiveIntegerField(blank=True, null=True, verbose_name='Expected Family Contribution')),
                ('pronouns', models.CharField(blank=True, default=None, max_length=255, verbose_name='pronoun')),
                ('ethnicity', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, verbose_name='ethnicity'), blank=True, null=True, size=None)),
                ('high_school_grad_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='high school graduation year')),
                ('income_quintile', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='income quintile')),
                ('found_from', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True, verbose_name='found from'), blank=True, null=True, size=None)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('organization', models.ManyToManyField(to='organization.Organization')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DeletedAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('accounts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
