# Generated by Django 3.1.1 on 2020-12-24 15:25

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ethnicity',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=255, verbose_name='ethnicity'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='income_quintile',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='income quintile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='preferred name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pronouns',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='pronoun'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='user type'),
        ),
    ]
