# Generated by Django 3.1.1 on 2020-12-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201129_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='phone number'),
        ),
    ]
