# Generated by Django 3.1.1 on 2021-02-07 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_auto_20210107_1452'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FieldCategory',
            new_name='Field',
        ),
        migrations.RemoveField(
            model_name='fieldscholarship',
            name='field_category',
        ),
        migrations.RemoveField(
            model_name='fieldscholarship',
            name='field_detail',
        ),
        migrations.RemoveField(
            model_name='fieldscholarship',
            name='scholarship',
        ),
        migrations.AlterModelOptions(
            name='educationcategory',
            options={'verbose_name': 'education category', 'verbose_name_plural': 'education categories'},
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'verbose_name': 'field', 'verbose_name_plural': 'fields'},
        ),
        migrations.AddField(
            model_name='scholarship',
            name='field',
            field=models.ManyToManyField(blank=True, to='scholarships.Field'),
        ),
        migrations.AlterField(
            model_name='educationscholarship',
            name='education_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scholarships.educationdetail'),
        ),
        migrations.AlterField(
            model_name='locationscholarship',
            name='location_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scholarships.locationdetail'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='website',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='FieldDetail',
        ),
        migrations.DeleteModel(
            name='FieldScholarship',
        ),
    ]
