# Generated by Django 3.0.1 on 2020-07-07 23:07

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='act_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='ACT score'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='efc',
            field=models.IntegerField(blank=True, null=True, verbose_name='Expected Family Contribution'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ethnicity',
            field=models.CharField(choices=[(None, ''), ('Asian', 'Asian'), ('Black/African', 'Black/African'), ('Hispanic/Latinx', 'Hispanic/Latinx'), ('Native American', 'Native American'), ('Pacific Islander', 'Pacific Islander'), ('White', 'White'), ('Prefer not to answer', 'Prefer not to answer'), ('Other', 'Other')], default=None, max_length=20, null=True, verbose_name='ethinicity'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ethnicity_other_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='GPA'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='highschool_graduation_year',
            field=models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default='2020', max_length=4, verbose_name='high school graduation year'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='preferred name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pronouns',
            field=models.CharField(choices=[(None, ''), ('He/his', 'He/his'), ('She/hers', 'She/hers'), ('They/their', 'They/their'), ('Other', 'Other')], default=None, max_length=20, null=True, verbose_name='pronoun'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pronouns_other_value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sat_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='SAT score'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='terms_and_conditions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Parent', 'Parent'), ('Counselor', 'Counselor')], default='Student', max_length=10, verbose_name='user type'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user is already registered with this email address'}, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
    ]
