# Generated by Django 3.0.1 on 2020-07-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200707_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='highschool_graduation_year',
            field=models.CharField(blank=True, choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=4, null=True, verbose_name='high school graduation year'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Parent', 'Parent'), ('Counselor', 'Counselor')], default='Student', max_length=10, null=True, verbose_name='user type'),
        ),
    ]
