# Generated by Django 3.0.1 on 2020-08-04 03:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200707_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ethnicity_other_value',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='highschool_graduation_year',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pronouns_other_value',
        ),
        migrations.AddField(
            model_name='customuser',
            name='found_from',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('parent', 'Parent'), ('school or district staff', 'School or District Staff'), ('friend', 'Friend'), ('other', 'Other')], max_length=25, verbose_name='found from'), default=list, size=None),
        ),
        migrations.AddField(
            model_name='customuser',
            name='found_from_other_value',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='high_school_grad_year',
            field=models.CharField(default=2020, max_length=4, verbose_name='high school graduation year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='income_quintile',
            field=models.CharField(blank=True, choices=[('lo', '$0 - $30,000'), ('m1', '$30,001 - $48,000'), ('m2', '$48,001 - $75,000'), ('h1', '$75,001 - $110,000'), ('h2', '$110,001+')], max_length=2, null=True, verbose_name='income quintile'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='act_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ACT score'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ethnicity',
            field=models.CharField(choices=[(None, ''), ('american indian and alaska native', 'American Indian/Alaska Native'), ('asian', 'Asian'), ('black and african', 'Black/African'), ('hispanic and latinx', 'Hispanic/Latinx'), ('native hawaiian and pacific islander', 'Native Hawaiian/Pacific Islander'), ('white', 'White'), ('other', 'Other')], default=None, max_length=40, null=True, verbose_name='ethinicity'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pronouns',
            field=models.CharField(choices=[(None, ''), ('he', 'He/His'), ('she', 'She/Hers'), ('they', 'They/their'), ('other', 'Other')], default=None, max_length=10, null=True, verbose_name='pronoun'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sat_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='SAT score'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('transfer', 'Transfer'), ('parent', 'Parent'), ('staff', 'Staff'), ('other', 'Other')], max_length=10, verbose_name='user type'),
        ),
    ]
