# Generated by Django 3.0.1 on 2020-08-02 20:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200802_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='found_from',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('parent', 'Parent'), ('school or district staff', 'School or District Staff'), ('friend', 'Friend'), ('other', 'Other')], max_length=25, verbose_name='found from'), default=None, null=True, size=None),
        ),
    ]
