# Generated by Django 3.1.1 on 2020-09-28 03:43

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20200923_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='tilt_partnership',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='types',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=None, null=True, size=None),
        ),
    ]
